export const fieldTypes = {
    TEXT: "TEXT",
    SELECT: "SELECT",
    SECTION: "SECTION",
    STEPPER: "STEPPER",
    CANVAS: "CANVAS",
    RADIO: "RADIO",
    CHECKBOX: "CHECKBOX",
    DATETIME: "DATETIME",
    FILEUPLOAD: "FILEUPLOAD",
    NUMBER: "NUMBER",
    PASSWORD: "PASSWORD",
    TEXTAREA: "TEXTAREA",
    GRID: "GRID"
}

export const VARIANT = {
    SECTION: "SECTION",
    STEPPER: "STEPPER",
    FIELD: "FIELD",
    GRID: "GRID"
}