export const fieldTypes = {
    TEXT: "TEXT",
    SELECT: "SELECT",
    SECTION: "SECTION",
    STEPPER: "STEPPER",
    RADIO: "RADIO",
    CHECKBOX: "CHECKBOX",
    DATETIME: "DATETIME",
    FILEUPLOAD: "FILEUPLOAD",
    NUMBER: "NUMBER",
    PASSWORD: "PASSWORD",
    TEXTAREA: "TEXTAREA"
}